"""The web window's colours, type and icons, generated from the Python theme.

    python -m src.app.webtheme        rewrite web/src/lib/generated/

src/gui/theme stays the one place where a colour is decided: its WCAG
contrast tests keep running in Python, and the page only ever uses the CSS
variables written here. tests/test_webtheme.py fails when the files are
out of date, so a token changed in Python cannot silently miss the page.
"""
import os
from dataclasses import fields

from src.gui.theme import DARK_THEME, LIGHT_THEME, get_theme
from src.gui.theme.images import Icons

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
OUT = os.path.join(ROOT, "web", "src", "lib", "generated")
HEADER = "Generated by src/app/webtheme.py from src/gui/theme. Do not edit; run python -m src.app.webtheme."

# Fonts for scripts the Segoe UI family lacks, as Windows itself uses them;
# the browser picks the first family that has a glyph, character by character.
SCRIPT_FALLBACKS = ('"Nirmala UI"', '"Yu Gothic UI"', '"Microsoft YaHei UI"', "sans-serif")
_STRONG = {"display", "title", "heading", "body_strong", "label", "small_strong", "micro"}


def _css_name(name):
    return name.replace("_", "-")


def _palette_block(theme):
    lines = [f"  --{_css_name(name)}: {value};" for name, value in theme.color_tokens().items()]
    lines.append(f"  color-scheme: {'dark' if theme.dark else 'light'};")
    return "\n".join(lines)


def _families(role, generic="sans-serif"):
    # Tk names the semibold faces as families of their own; CSS asks for the
    # regular family at weight 600 instead.
    names = []
    for family in role.families + (role.fallback,):
        family = family.replace(" Semibold", "")
        quoted = f'"{family}"'
        if quoted not in names:
            names.append(quoted)
    return ", ".join(names + list(SCRIPT_FALLBACKS[:-1]) + [generic])


def theme_css():
    light, dark = get_theme(LIGHT_THEME), get_theme(DARK_THEME)
    typography, metrics = light.typography, light.metrics
    # Plain [data-theme] selectors, not :root[...]: any element can then show
    # the other theme, as the theme cards in Settings do.
    lines = [f"/* {HEADER} */", "", ':root,\n[data-theme="paper"] {', _palette_block(light), "}", "",
             '[data-theme="night"] {', _palette_block(dark), "}", "", ":root {"]
    for role in fields(typography):
        value = getattr(typography, role.name)
        if not hasattr(value, "families"):
            continue
        name = _css_name(role.name)
        generic = "monospace" if role.name == "mono" else "sans-serif"
        lines.append(f"  --font-{name}: {_families(value, generic)};")
        lines.append(f"  --size-{name}: {value.size}pt;")
        lines.append(f"  --weight-{name}: {600 if role.name in _STRONG else 400};")
    icon_fonts = ", ".join(f'"{family}"' for family in typography.icon_families)
    lines.append(f"  --font-icon: {icon_fonts};")
    for field in fields(metrics):
        value = getattr(metrics, field.name)
        lines.append(f"  --{_css_name(field.name)}: {value}px;")
    lines.append("}")
    return "\n".join(lines) + "\n"


def icons_ts():
    glyphs = {name: value for name, value in vars(Icons).items() if name.isupper()}
    lines = [f"// {HEADER}", "// Segoe Fluent Icons / Segoe MDL2 Assets glyphs by meaning.", "",
             "export const Icons = {"]
    lines += [f'  {name}: "\\u{ord(glyph):04X}",' for name, glyph in glyphs.items()]
    lines += ["} as const;", "", "export type IconName = keyof typeof Icons;", ""]
    return "\n".join(lines)


FILES = {"theme.css": theme_css, "icons.ts": icons_ts}


def write(out=OUT):
    os.makedirs(out, exist_ok=True)
    for name, make in FILES.items():
        with open(os.path.join(out, name), "w", encoding="utf-8", newline="\n") as f:
            f.write(make())


if __name__ == "__main__":
    write()
    print(f"wrote {', '.join(FILES)} to {os.path.relpath(OUT, ROOT)}")
