from src.core.config_manager import cfg

_STRINGS = {
    "tr": {
        # ── Tab İsimleri ──
        "txt_compress":     "Sıkıştır",
        "txt_split":        "Kes",
        "txt_merge":        "Birleştir",
        "txt_edit":         "Düzenle",
        "txt_convert":      "Dönüştür",
        "txt_security":     "Güvenlik",
        "txt_advanced":     "Gelişmiş",
        "txt_batch":        "Toplu İşlemler",
        "txt_settings":     "Ayarlar",

        # ── Genel / Ortak ──
        "str_ready":            "Hazır",
        "str_browse":           "Gözat",
        "str_save_as":          "Konum Seç",
        "str_apply":            "Uygula",
        "str_start":            "Başlat / Uygula",
        "str_select_file":      "Dosya Seç",
        "str_select_dir":       "Klasör Seç",
        "str_info":             "Bilgi",
        "str_error":            "Hata",
        "str_success":          "Başarılı",
        "str_done":             "Tamamlandı",
        "str_failed":           "Başarısız",
        "str_processing":       "İşleniyor...",
        "str_add":              "Ekle",
        "str_remove":           "Kaldır",
        "str_up":               "Yukarı",
        "str_down":             "Aşağı",
        "str_save":             "Kaydet",
        "str_select":           "Seç",
        "str_delete":           "Sil",
        "str_cancel":           "İptal",
        "str_close":            "Kapat",
        "output_action_hint":   "Kaydetme konumunu seçtikten sonra alttaki \"{action}\" düğmesine basın.",

        # ── Dosya Seçimi Diyalogları ──
        "str_file_selection":       "Dosya Seçimi",
        "str_input_pdf":            "Girdi PDF",
        "str_output_pdf":           "Çıktı PDF",
        "str_input_pdf_image":      "Girdi PDF / Resim",
        "str_output_dir_file":      "Çıktı Dizin/Dosya",
        "str_output_folder":        "Çıktı Klasörü",
        "str_input_folder":         "Girdi KLASÖRÜ",
        "str_output_folder_label":  "Çıktı KLASÖRÜ",

        # ── Hata / Doğrulama Mesajları ──
        "err_select_valid_pdf":     "Geçerli bir girdi PDF seçin.",
        "err_select_valid_file":    "Geçerli bir PDF seçin.",
        "err_set_output":           "Çıktı yolunu belirleyin.",
        "err_output_not_created":   "Çıktı dosyası oluşturulamadı.",
        "err_select_quality":       "Kalite seçin: ",
        "err_enter_page_numbers":   "Geçerli sayfa numaraları girin.",
        "err_min_2_pdf":            "En az 2 PDF dosyası ekleyin.",
        "err_select_valid_word":    "Geçerli bir Word dosyası seçin.",
        "err_select_valid_ppt":     "Geçerli bir PowerPoint dosyası seçin.",
        "err_select_valid_excel":   "Geçerli bir Excel dosyası seçin.",
        "err_add_min_1_image":      "En az bir resim ekleyin.",
        "err_set_output_folder":    "Çıktı klasörü belirleyin.",
        "err_select_valid_input_dir": "Lütfen geçerli bir girdi klasörü seçin.",
        "err_select_valid_output_dir": "Lütfen geçerli bir çıktı klasörü seçin.",
        "err_watermark_empty":      "Filigran metni boş olamaz.",
        "err_unknown_op":           "Bilinmeyen işlem: ",
        "err_critical":             "Kritik Hata",
        "err_pdf_open_fail":        "PDF Açılamadı: ",
        "err_set_output_file":      "Çıktı dosyası belirleyin.",

        # ── Drag & Drop ──
        "str_drag_drop_hint": "Bir PDF dosyasını pencereye sürükleyip bırakabilirsiniz.",
        "str_files_added_to_list": " dosya listeye eklendi.",

        # ── Sıkıştır (Compress) Sekmesi ──
        "compress_settings":        "Sıkıştırma Ayarları",
        "compress_quality":         "Kalite",
        "compress_quality_hint":    "screen: en fazla sıkıştırma, prepress: en yüksek kalite",
        "compress_btn":             "PDF Sıkıştır",
        "compress_running":         "PDF sıkıştırılıyor...",
        "compress_done":            "Sıkıştırma tamamlandı.",
        "compress_fail":            "Sıkıştırma başarısız.",
        "compress_result_original": "Orijinal: ",
        "compress_result_compressed": "Sıkıştırılmış: ",
        "compress_result_quality":  "Kalite: ",
        "compress_result_saved":    "Kaydedildi:\n",
        "compress_dialog_input":    "Girdi PDF seç",
        "compress_dialog_output":   "Sıkıştırılmış PDF kaydet",

        # ── Kes (Split) Sekmesi ──
        "split_page_range":         "Sayfa Aralığı",
        "split_start":              "Başlangıç",
        "split_end":                "Bitiş",
        "split_hint":               "Örnek: 1-100 = ilk 100 sayfa,  101-200 = 101 ile 200 arası",
        "split_btn":                "PDF Kes",
        "split_running":            "PDF kesiliyor... (Sayfa {start}-{end})",
        "split_done":               "Kesme tamamlandı.",
        "split_fail":               "Kesme başarısız.",
        "split_total_pages":        "Toplam {count} sayfa",
        "split_page_read_err":      "Sayfa sayısı okunamadı: ",
        "split_dialog_input":       "Kesilecek PDF seç",
        "split_dialog_output":      "Kesilen PDF kaydet",
        "split_result":             "Orijinal: {orig:.2f} MB\nKesilen: {result:.2f} MB\nSayfa: {start}-{end} ({count} sayfa)\nKaydedildi:\n{output}",

        # ── Birleştir (Merge) Sekmesi ──
        "merge_pdf_files":          "PDF Dosyaları",
        "merge_btn":                "PDF Birleştir",
        "merge_running":            "{count} dosya birleştiriliyor...",
        "merge_done":               "Birleştirme tamamlandı.",
        "merge_fail":               "Birleştirme başarısız.",
        "merge_dialog_input":       "PDF dosyaları seç",
        "merge_dialog_output":      "Birleşik PDF kaydet",
        "merge_result":             "{count} dosya birleştirildi\nToplam: {pages} sayfa, {size:.2f} MB\nKaydedildi:\n{output}",

        # ── Düzenle (Edit) Sekmesi ──
        "edit_operation":           "İşlem",
        "edit_mode_delete":         "Sayfa Sil",
        "edit_mode_rotate":         "Sayfa Döndür",
        "edit_mode_reorder":        "Sayfa Sırala",
        "edit_pages_to_delete":     "Silinecek Sayfalar",
        "edit_delete_hint":         "Örnek: 3, 5, 12-15",
        "edit_pages_to_rotate":     "Döndürülecek Sayfalar",
        "edit_rotate_hint":         "Boş bırakırsanız tüm sayfalar döndürülür",
        "edit_angle":               "Açı:",
        "edit_angle_hint":          "derece (saat yönü)",
        "edit_new_order":           "Yeni Sayfa Sıralaması",
        "edit_order_hint":          "Örnek: 5, 3, 1, 2, 4  (ters çevirmek için: 5, 4, 3, 2, 1)",
        "edit_running":             "{mode} uygulanıyor...",
        "edit_done":                "Düzenleme tamamlandı.",
        "edit_fail":                "Düzenleme başarısız.",
        "edit_dialog_input":        "Düzenlenecek PDF seç",
        "edit_dialog_output":       "Düzenlenmiş PDF kaydet",
        "edit_err_enter_delete":    "Silinecek sayfa numaralarını girin.",
        "edit_err_enter_order":     "Yeni sayfa sıralamasını girin.",
        "edit_result_delete":       "{count} sayfa silindi.\nKalan: {remaining} sayfa\nKaydedildi:\n{output}",
        "edit_result_rotate":       "{count} sayfa {angle} derece döndürüldü.\nKaydedildi:\n{output}",
        "edit_result_reorder":      "Sayfalar yeniden sıralandı ({count} sayfa).\nKaydedildi:\n{output}",
        "edit_total_pages":         "Toplam {count} sayfa",

        # ── Dönüştür (Convert) Sekmesi ──
        "convert_type":             "Dönüştürme Türü",
        "convert_pdf2img":          "PDF → Resim",
        "convert_img2pdf":          "Resim → PDF",
        "convert_pdf2word":         "PDF → Word",
        "convert_word2pdf":         "Word → PDF",
        "convert_ppt2pdf":          "PowerPoint → PDF",
        "convert_excel2pdf":        "Excel → PDF",
        "convert_pdf2txt":          "PDF → Metin (TXT)",
        "convert_btn":              "Dönüştür",
        "convert_running":          "{mode} işleniyor...",
        "convert_done":             "Dönüştürme tamamlandı.",
        "convert_fail":             "Dönüştürme başarısız.",
        "convert_image_files":      "Resim Dosyaları",
        "convert_output_word":      "Çıktı Word (.docx)",
        "convert_input_word":       "Girdi Word (.docx)",
        "convert_input_ppt":        "Girdi PowerPoint (.ppt, .pptx)",
        "convert_input_excel":      "Girdi Excel (.xls, .xlsx)",
        "convert_output_txt":       "Çıktı Metin (.txt)",
        "convert_page_size":        "Sayfa Boyutu:",
        "convert_original":         "Orijinal",
        "convert_images_label":     "Resimler",
        "convert_dialog_pdf":       "PDF seç",
        "convert_dialog_folder":    "Çıktı klasörü seç",
        "convert_dialog_img":       "Resim seç",
        "convert_dialog_pdf_save":  "PDF kaydet",
        "convert_dialog_word_save": "Word kaydet",
        "convert_result_p2i":       "{count} sayfa resme dönüştürüldü.\nDPI: {dpi}\nKlasör:\n{folder}",
        "convert_result_i2p":       "{count} resim PDF'e dönüştürüldü.\nBoyut: {size:.2f} MB\nKaydedildi:\n{output}",
        "convert_result_p2w":       "PDF başarıyla Word'e dönüştürüldü.\nKaydedildi:\n{output}",
        "convert_result_w2p":       "Word başarıyla PDF'e dönüştürüldü.\nKaydedildi:\n{output}",
        "convert_result_ppt2pdf":   "PowerPoint başarıyla PDF'e dönüştürüldü.\nKaydedildi:\n{output}",
        "convert_result_excel2pdf": "Excel başarıyla PDF'e dönüştürüldü.\nKaydedildi:\n{output}",
        "convert_result_pdf2txt":   "PDF metin olarak dışa aktarıldü.\nKaydedildi:\n{output}",

        # ── Güvenlik (Security) Sekmesi ──
        "security_op_type":         "İşlem Türü",
        "security_encrypt":         "Şifrele",
        "security_decrypt":         "Şifre Kaldır",
        "security_watermark":       "Filigran Ekle",
        "security_password":        "Parola:",
        "security_watermark_text":  "Filigran Metni:",
        "security_running":         "{mode} işleniyor...",
        "security_dialog_input":    "PDF Seç",
        "security_dialog_output":   "PDF Kaydet",
        "security_result_encrypt":  "PDF başarıyla şifrelendi.\nKaydedildi:\n{output}",
        "security_result_decrypt":  "PDF şifresi başarıyla kaldırıldı.\nKaydedildi:\n{output}",
        "security_result_watermark": "Filigran eklendi.\nKaydedildi:\n{output}",

        # ── Gelişmiş (Advanced) Sekmesi ──
        "adv_operation":            "Gelişmiş İşlem",
        "adv_preview":              "Önizleme Oluştur",
        "adv_ocr":                  "OCR (Metin Tanıma)",
        "adv_metadata":             "Meta Veri Düzenle",
        "adv_signature":            "Islak İmza (Görsel)",
        "adv_preview_hint":         "Önizleme penceresini ayrı bir sekmede açar. Sayfaları görebilirsiniz.",
        "adv_ocr_hint":             "Tesseract-OCR kullanılarak PDF içindeki resimler metne (.txt) dökülür.",
        "adv_tess_warning":         "Dikkat: Tesseract bilgisayarınızda kurulu olmalıdır.",
        "adv_tess_not_installed":   "⚠ Tesseract Kurulu Değil! OCR yapabilmek için kurmalısınız.",
        "adv_tess_installed":       "✓ Tesseract Kurulu ve Hazır.",
        "adv_tess_install_btn":     "⬇ Otomatik İndir ve Kur (Winget)",
        "adv_tess_installing":      "⚙ Kuruluyor... Lütfen bekleyin",
        "adv_tess_install_ok":      "Tesseract başarıyla kuruldu! Artık OCR yapabilirsiniz.",
        "adv_tess_install_title":   "Kurulum Tamamlandı",
        "adv_read_meta_btn":        "Güncel Metadataları Oku",
        "adv_meta_title":           "Başlık (Title):",
        "adv_meta_author":          "Yazar (Author):",
        "adv_meta_subject":         "Konu (Subject):",
        "adv_meta_creator":         "Oluşturan (Creator):",
        "adv_meta_clean":           "Tümünü Temizle (Boşalt)",
        "adv_meta_read_ok":         "Mevcut metadata okundu.",
        "adv_sig_image":            "İmza Resmi (.png/.jpg)",
        "adv_sig_choose":           "Resim Seç",
        "adv_sig_page":             "Sayfa (1-X):",
        "adv_sig_x":                "X Koordinatı (pt):",
        "adv_sig_y":                "Y Koordinatı (pt):",
        "adv_sig_scale":            "Ölçek Çarpanı (Varsayılan 1.0):",
        "adv_dialog_txt_save":      "Metin (.txt) Kaydet",
        "adv_dialog_pdf_save":      "PDF Kaydet",
        "adv_dialog_sig_img":       "İmza Resmi",
        "adv_result_ocr":           "OCR tamamlandı, metne döküldü.\n{output}",
        "adv_result_meta":          "Meta veriler düzenlendi.\n{output}",
        "adv_result_sig":           "İmza eklendi.\n{output}",

        # ── Viewer ──
        "viewer_title":             "PDF Aura - Gelişmiş Önizleyici",
        "viewer_prev":              "<< Önceki",
        "viewer_next":              "Sonraki >>",
        "viewer_page":              "Sayfa {current} / {total}",
        "viewer_zoom_in":           "Zoom In (+)",
        "viewer_zoom_out":          "Zoom Out (-)",

        # ── Toplu İşlemler (Batch) Sekmesi ──
        "batch_main_type":          "Ana İşlem Tipi",
        "batch_compress":           "Toplu Sıkıştırma",
        "batch_convert":            "Toplu Dönüştürme",
        "batch_rename":             "Toplu Yeniden Adlandırma",
        "batch_compress_quality":   "Sıkıştırma Kalitesi:",
        "batch_radio_pdf2img":      "PDF → Tüm Sayfaları Resimlere (Ayıkla)",
        "batch_radio_img2pdf":      "Resimler → Toplu Tekil PDF'lere dönüştür",
        "batch_rename_rule":        "Adlandırma Kuralı:",
        "batch_rename_hint":        "Tavsiye Edilen Parametreler:\n[ORİJİNAL_AD] [SAYFA_SAYISI] [BOYUT] [SIRA] [TARİH]",
        "batch_start_btn":          "Başlat / İşlemi Başlat",
        "batch_dialog_input":       "Kaynak Klasör Seç",
        "batch_dialog_output":      "Çıktı Klasör Seç",
        "batch_log_started":        "--- TOPLU İŞLEM BAŞLADI ---\nKaynak: {path}\n",
        "batch_log_ended":          "\n--- İŞLEM SONA ERDİ ---",
        "batch_progress":           "İşleniyor... %{pct} ({cur}/{total})",
        "batch_done":               "Tamamlandı.",
        "batch_result":             "Toplu işlem tamamlandı!\nBaşarılı: {succ}\nHata: {errs}",
        "batch_result_errors":      "\n\nHatalar uygulamanın kaydettiği .txt raporuna yazıldı. ({dir} klasöründe)",
        "batch_result_title":       "Bitti",
        "batch_success_count":      "Başarılı: {succ} // Hata: {errs}",

        # ── Batch Core (Rapor & Log) ──
        "batch_no_pdf_found":       "Kaynak klasörde geçerli PDF bulunamadı.",
        "batch_log_compressed":     "Sıkıştırıldı",
        "batch_log_pages_extracted": "Sayfalara ayrıldı",
        "batch_log_pdf_created":    "PDF Üretildi",
        "batch_report_date":        "Tarih",
        "batch_report_total":       "Toplam İşlenen Dosya",
        "batch_report_success":     "Başarılı",
        "batch_report_errors":      "Hata Alan",
        "batch_report_error_details": "HATA DETAYLARI",
        "batch_report_no_errors":   "Hiçbir hata yaşanmadı. Tüm işlemler başarılı.",

        # ── Ayarlar (Settings) Sekmesi ──
        "settings_appearance":      "Görünüm ve Davranış",
        "settings_lang":            "Uygulama Dili:",
        "settings_tray":            "X (Kapat) tuşuna basıldığında Sistem Tepsisine küçült",
        "settings_sound":           "İşlem bitişlerinde uyarı sesi çal",
        "settings_file_ops":        "Dosya İşlemleri",
        "settings_default_dir":     "Varsayılan Çıktı Klasörü:",
        "settings_history":         "Geçmiş ve Gizlilik",
        "settings_clear_history":   "Son Dosyalar Kaydını Temizle",
        "settings_save_btn":        "Ayarları Kaydet",
        "settings_cleared":         "Geçmiş kayıtlar temizlendi.",
        "settings_saved":           "Ayarlar kaydedildi.\nDil değişikliğinin uygulanması için uygulamayı yeniden başlatmanızı tavsiye ederiz.",

        # ── System Tray ──
        "tray_open":   "Aç",
        "tray_quit":   "Çıkış",

        # ── Header ──
        "header_subtitle": "Sıkıştır  •  Kes  •  Birleştir  •  Düzenle  •  Dönüştür  •  Güvenlik  •  Gelişmiş  •  Toplu İşlemler",
        "sidebar_workspace": "ÇALIŞMA ALANI",
        "sidebar_drag_drop": "SÜRÜKLE BIRAK",
        "page_meta_compress_eyebrow": "HIZLI ARAÇ",
        "page_meta_compress_title": "PDF sıkıştırma",
        "page_meta_compress_body": "Dosya boyutunu azalt, kalite profilini seç ve sonucu anında dışa aktar.",
        "page_meta_organize_eyebrow": "SAYFA ÇALIŞMA ALANI",
        "page_meta_organize_title": "Kes, birleştir, düzenle",
        "page_meta_organize_body": "Tüm sayfa operasyonlarını tek yerde topla; parçalama, sıralama ve birleştirme işleri burada.",
        "page_meta_convert_eyebrow": "DÖNÜŞTÜRME MERKEZİ",
        "page_meta_convert_title": "Format çevirici",
        "page_meta_convert_body": "PDF, Office ve görsel formatları arasında akıcı geçişler için tek panel.",
        "page_meta_security_eyebrow": "KORUMA",
        "page_meta_security_title": "Şifre ve filigran",
        "page_meta_security_body": "PDF'leri koru, şifreyi kaldır veya belgeyi filigranla işaretle.",
        "page_meta_advanced_eyebrow": "GELİŞMİŞ ARAÇLAR",
        "page_meta_advanced_title": "Önizleme, OCR, metadata, imza",
        "page_meta_advanced_body": "Yüksek seviye doküman işlerini aynı yüzeyde yönet.",
        "page_meta_batch_eyebrow": "OTOMASYON",
        "page_meta_batch_title": "Toplu işlemler",
        "page_meta_batch_body": "Klasör bazlı toplu sıkıştırma, dönüştürme ve yeniden adlandırma akışları.",
        "feedback_ready_badge": "HAZIR",
        "feedback_ready_title": "Araç kullanıma hazır",
        "feedback_ready_body": "Bir dosya seçip işlemi başlatabilirsin.",
        "feedback_busy_badge": "İŞLENİYOR",
        "feedback_busy_title": "İşlem devam ediyor",
        "feedback_done_badge": "TAMAMLANDI",
        "feedback_error_badge": "HATA",
        "feedback_info_badge": "BİLGİ",
        "feedback_open_output": "Çıktıyı Aç",
        "feedback_open_folder": "Klasörü Aç",
        "preview_title": "Önizleme",
        "preview_subtitle": "Seçili PDF burada özetlenir.",
        "preview_open": "Tam Önizleme",
        "preview_open_folder": "Klasörü Aç",
        "preview_empty_title": "Bir PDF seç",
        "preview_empty_body": "Seçim yapıldığında ilk sayfa önizlemesi burada gösterilir.",
        "preview_empty_sources": "Desteklenen kaynaklar: sıkıştırma, kes, birleştir, düzenle, güvenlik ve gelişmiş araçlar.",
        "preview_unavailable": "Önizleme yüklenemedi",
        "preview_pages_mb": "{pages} sayfa  •  {size:.2f} MB",
        "batch_log_title": "İşlem Günlüğü",

        # ── Belge Tarayıcı (Scanner) ──
        "scanner_title":            "Belge Tara",
        "scanner_select_photo":     "Fotoğraf Seç",
        "scanner_select_hint":      "Tararken kullanılacak fotoğrafı seçin (JPG, PNG, BMP).",
        "scanner_input_image":      "Girdi Fotoğrafı",
        "scanner_output_pdf":       "Çıktı PDF",
        "scanner_scan_mode":        "Tarama Stili",
        "scanner_mode_original":    "Orijinal (Yalnızca Kırp)",
        "scanner_mode_clean_doc":   "Temiz Belge (Beyaz Arka Plan)",
        "scanner_mode_bw":          "Siyah-Beyaz",
        "scanner_mode_grayscale":   "Gri Tonlama",
        "scanner_mode_sharp":       "Keskin Belge",
        "scanner_corners_hint":     "Belgenin 4 köşesini sürükleyerek ayarlayın.",
        "scanner_auto_detect":      "Otomatik Algıla",
        "scanner_reset_corners":    "Sıfırla",
        "scanner_rotate_cw":        "↻ Sağa Döndür",
        "scanner_rotate_ccw":       "↺ Sola Döndür",
        "scanner_btn":              "Tara ve PDF Oluştur",
        "scanner_running":          "Belge taranıyor...",
        "scanner_done":             "Tarama Tamamlandı",
        "scanner_fail":             "Tarama Başarısız",
        "scanner_result":           "Belge başarıyla tarandı ve PDF olarak kaydedildi.\nKaydedildi:\n{output}",
        "scanner_result_multi":     "{count} sayfa tarandı ve tek PDF olarak kaydedildi.\nKaydedildi:\n{output}",
        "scanner_no_image":         "Lütfen önce bir fotoğraf seçin.",
        "scanner_preview":          "Önizleme",
        "scanner_crop_area":        "Kırpma Alanı",
        "scanner_add_photo":        "Fotoğraf Ekle",
        "scanner_remove_photo":     "Kaldır",
        "scanner_page_count":       "{count} sayfa",
        "scanner_page_label":       "Sayfa {num}/{total}",
        "scanner_no_pages":         "Henüz fotoğraf eklenmedi.",
        "scanner_fullscreen_crop":  "🔍 Tam Ekran Kırp",
        "scanner_fullscreen_close": "Tam Ekrandan Çık",
        "err_select_valid_image":   "Geçerli bir resim dosyası seçin.",

        # ── Performans Optimizasyonu ──
        "perf_cancel":              "İptal",
        "perf_cancelling":          "İptal ediliyor...",
        "perf_cancelled":           "İptal Edildi",
        "perf_cancelled_msg":       "İşlem kullanıcı tarafından iptal edildi.",
        "perf_cancelled_badge":     "İPTAL",
    },

    "en": {
        # ── Tab Names ──
        "txt_compress":     "Compress",
        "txt_split":        "Split",
        "txt_merge":        "Merge",
        "txt_edit":         "Edit",
        "txt_convert":      "Convert",
        "txt_security":     "Security",
        "txt_advanced":     "Advanced",
        "txt_batch":        "Batch Process",
        "txt_settings":     "Settings",

        # ── General / Common ──
        "str_ready":            "Ready",
        "str_browse":           "Browse",
        "str_save_as":          "Choose Location",
        "str_apply":            "Apply",
        "str_start":            "Start / Apply",
        "str_select_file":      "Select File",
        "str_select_dir":       "Select Folder",
        "str_info":             "Info",
        "str_error":            "Error",
        "str_success":          "Success",
        "str_done":             "Completed",
        "str_failed":           "Failed",
        "str_processing":       "Processing...",
        "str_add":              "Add",
        "str_remove":           "Remove",
        "str_up":               "Up",
        "str_down":             "Down",
        "str_save":             "Save",
        "str_select":           "Select",
        "str_delete":           "Delete",
        "str_cancel":           "Cancel",
        "str_close":            "Close",
        "output_action_hint":   "After choosing the output location, click \"{action}\" below.",

        # ── File Selection Dialogs ──
        "str_file_selection":       "File Selection",
        "str_input_pdf":            "Input PDF",
        "str_output_pdf":           "Output PDF",
        "str_input_pdf_image":      "Input PDF / Image",
        "str_output_dir_file":      "Output Dir/File",
        "str_output_folder":        "Output Folder",
        "str_input_folder":         "Input FOLDER",
        "str_output_folder_label":  "Output FOLDER",

        # ── Error / Validation Messages ──
        "err_select_valid_pdf":     "Select a valid input PDF.",
        "err_select_valid_file":    "Select a valid PDF.",
        "err_set_output":           "Set the output path.",
        "err_output_not_created":   "Output file could not be created.",
        "err_select_quality":       "Select quality: ",
        "err_enter_page_numbers":   "Enter valid page numbers.",
        "err_min_2_pdf":            "Add at least 2 PDF files.",
        "err_select_valid_word":    "Select a valid Word file.",
        "err_select_valid_ppt":     "Select a valid PowerPoint file.",
        "err_select_valid_excel":   "Select a valid Excel file.",
        "err_add_min_1_image":      "Add at least one image.",
        "err_set_output_folder":    "Set the output folder.",
        "err_select_valid_input_dir": "Please select a valid input folder.",
        "err_select_valid_output_dir": "Please select a valid output folder.",
        "err_watermark_empty":      "Watermark text cannot be empty.",
        "err_unknown_op":           "Unknown operation: ",
        "err_critical":             "Critical Error",
        "err_pdf_open_fail":        "Could not open PDF: ",
        "err_set_output_file":      "Set the output file.",

        # ── Drag & Drop ──
        "str_drag_drop_hint": "You can drag and drop a PDF file into the window.",
        "str_files_added_to_list": " file(s) added to list.",

        # ── Compress Tab ──
        "compress_settings":        "Compression Settings",
        "compress_quality":         "Quality",
        "compress_quality_hint":    "screen: max compression, prepress: highest quality",
        "compress_btn":             "Compress PDF",
        "compress_running":         "Compressing PDF...",
        "compress_done":            "Compression completed.",
        "compress_fail":            "Compression failed.",
        "compress_result_original": "Original: ",
        "compress_result_compressed": "Compressed: ",
        "compress_result_quality":  "Quality: ",
        "compress_result_saved":    "Saved:\n",
        "compress_dialog_input":    "Select input PDF",
        "compress_dialog_output":   "Save compressed PDF",

        # ── Split Tab ──
        "split_page_range":         "Page Range",
        "split_start":              "Start",
        "split_end":                "End",
        "split_hint":               "Example: 1-100 = first 100 pages,  101-200 = pages 101 to 200",
        "split_btn":                "Split PDF",
        "split_running":            "Splitting PDF... (Page {start}-{end})",
        "split_done":               "Splitting completed.",
        "split_fail":               "Splitting failed.",
        "split_total_pages":        "Total {count} pages",
        "split_page_read_err":      "Could not read page count: ",
        "split_dialog_input":       "Select PDF to split",
        "split_dialog_output":      "Save split PDF",
        "split_result":             "Original: {orig:.2f} MB\nSplit: {result:.2f} MB\nPages: {start}-{end} ({count} pages)\nSaved:\n{output}",

        # ── Merge Tab ──
        "merge_pdf_files":          "PDF Files",
        "merge_btn":                "Merge PDFs",
        "merge_running":            "Merging {count} files...",
        "merge_done":               "Merge completed.",
        "merge_fail":               "Merge failed.",
        "merge_dialog_input":       "Select PDF files",
        "merge_dialog_output":      "Save merged PDF",
        "merge_result":             "{count} files merged\nTotal: {pages} pages, {size:.2f} MB\nSaved:\n{output}",

        # ── Edit Tab ──
        "edit_operation":           "Operation",
        "edit_mode_delete":         "Delete Pages",
        "edit_mode_rotate":         "Rotate Pages",
        "edit_mode_reorder":        "Reorder Pages",
        "edit_pages_to_delete":     "Pages to Delete",
        "edit_delete_hint":         "Example: 3, 5, 12-15",
        "edit_pages_to_rotate":     "Pages to Rotate",
        "edit_rotate_hint":         "Leave empty to rotate all pages",
        "edit_angle":               "Angle:",
        "edit_angle_hint":          "degrees (clockwise)",
        "edit_new_order":           "New Page Order",
        "edit_order_hint":          "Example: 5, 3, 1, 2, 4  (to reverse: 5, 4, 3, 2, 1)",
        "edit_running":             "Applying {mode}...",
        "edit_done":                "Edit completed.",
        "edit_fail":                "Edit failed.",
        "edit_dialog_input":        "Select PDF to edit",
        "edit_dialog_output":       "Save edited PDF",
        "edit_err_enter_delete":    "Enter page numbers to delete.",
        "edit_err_enter_order":     "Enter the new page order.",
        "edit_result_delete":       "{count} pages deleted.\nRemaining: {remaining} pages\nSaved:\n{output}",
        "edit_result_rotate":       "{count} pages rotated {angle} degrees.\nSaved:\n{output}",
        "edit_result_reorder":      "Pages reordered ({count} pages).\nSaved:\n{output}",
        "edit_total_pages":         "Total {count} pages",

        # ── Convert Tab ──
        "convert_type":             "Conversion Type",
        "convert_pdf2img":          "PDF → Image",
        "convert_img2pdf":          "Image → PDF",
        "convert_pdf2word":         "PDF → Word",
        "convert_word2pdf":         "Word → PDF",
        "convert_ppt2pdf":          "PowerPoint → PDF",
        "convert_excel2pdf":        "Excel → PDF",
        "convert_pdf2txt":          "PDF → Text (TXT)",
        "convert_btn":              "Convert",
        "convert_running":          "Processing {mode}...",
        "convert_done":             "Conversion completed.",
        "convert_fail":             "Conversion failed.",
        "convert_image_files":      "Image Files",
        "convert_output_word":      "Output Word (.docx)",
        "convert_input_word":       "Input Word (.docx)",
        "convert_input_ppt":        "Input PowerPoint (.ppt, .pptx)",
        "convert_input_excel":      "Input Excel (.xls, .xlsx)",
        "convert_output_txt":       "Output Text (.txt)",
        "convert_page_size":        "Page Size:",
        "convert_original":         "Original",
        "convert_images_label":     "Images",
        "convert_dialog_pdf":       "Select PDF",
        "convert_dialog_folder":    "Select output folder",
        "convert_dialog_img":       "Select images",
        "convert_dialog_pdf_save":  "Save PDF",
        "convert_dialog_word_save": "Save Word",
        "convert_result_p2i":       "{count} pages converted to images.\nDPI: {dpi}\nFolder:\n{folder}",
        "convert_result_i2p":       "{count} images converted to PDF.\nSize: {size:.2f} MB\nSaved:\n{output}",
        "convert_result_p2w":       "PDF successfully converted to Word.\nSaved:\n{output}",
        "convert_result_w2p":       "Word successfully converted to PDF.\nSaved:\n{output}",
        "convert_result_ppt2pdf":   "PowerPoint successfully converted to PDF.\nSaved:\n{output}",
        "convert_result_excel2pdf": "Excel successfully converted to PDF.\nSaved:\n{output}",
        "convert_result_pdf2txt":   "PDF successfully extracted to text.\nSaved:\n{output}",

        # ── Security Tab ──
        "security_op_type":         "Operation Type",
        "security_encrypt":         "Encrypt",
        "security_decrypt":         "Remove Password",
        "security_watermark":       "Add Watermark",
        "security_password":        "Password:",
        "security_watermark_text":  "Watermark Text:",
        "security_running":         "Processing {mode}...",
        "security_dialog_input":    "Select PDF",
        "security_dialog_output":   "Save PDF",
        "security_result_encrypt":  "PDF encrypted successfully.\nSaved:\n{output}",
        "security_result_decrypt":  "PDF password removed successfully.\nSaved:\n{output}",
        "security_result_watermark": "Watermark added.\nSaved:\n{output}",

        # ── Advanced Tab ──
        "adv_operation":            "Advanced Operation",
        "adv_preview":              "Create Preview",
        "adv_ocr":                  "OCR (Text Recognition)",
        "adv_metadata":             "Edit Metadata",
        "adv_signature":            "Visual Signature",
        "adv_preview_hint":         "Opens the preview window in a separate tab. You can browse pages.",
        "adv_ocr_hint":             "Text is extracted from images inside the PDF using Tesseract-OCR (.txt).",
        "adv_tess_warning":         "Note: Tesseract must be installed on your computer.",
        "adv_tess_not_installed":   "⚠ Tesseract is not installed! You need to install it for OCR.",
        "adv_tess_installed":       "✓ Tesseract is installed and ready.",
        "adv_tess_install_btn":     "⬇ Auto Download & Install (Winget)",
        "adv_tess_installing":      "⚙ Installing... Please wait",
        "adv_tess_install_ok":      "Tesseract installed successfully! You can now use OCR.",
        "adv_tess_install_title":   "Installation Complete",
        "adv_read_meta_btn":        "Read Current Metadata",
        "adv_meta_title":           "Title:",
        "adv_meta_author":          "Author:",
        "adv_meta_subject":         "Subject:",
        "adv_meta_creator":         "Creator:",
        "adv_meta_clean":           "Clear All (Empty)",
        "adv_meta_read_ok":         "Current metadata was read.",
        "adv_sig_image":            "Signature Image (.png/.jpg)",
        "adv_sig_choose":           "Select Image",
        "adv_sig_page":             "Page (1-X):",
        "adv_sig_x":                "X Coordinate (pt):",
        "adv_sig_y":                "Y Coordinate (pt):",
        "adv_sig_scale":            "Scale Factor (Default 1.0):",
        "adv_dialog_txt_save":      "Save Text (.txt)",
        "adv_dialog_pdf_save":      "Save PDF",
        "adv_dialog_sig_img":       "Signature Image",
        "adv_result_ocr":           "OCR completed, extracted to text.\n{output}",
        "adv_result_meta":          "Metadata updated.\n{output}",
        "adv_result_sig":           "Signature added.\n{output}",

        # ── Viewer ──
        "viewer_title":             "PDF Aura - Advanced Viewer",
        "viewer_prev":              "<< Previous",
        "viewer_next":              "Next >>",
        "viewer_page":              "Page {current} / {total}",
        "viewer_zoom_in":           "Zoom In (+)",
        "viewer_zoom_out":          "Zoom Out (-)",

        # ── Batch Tab ──
        "batch_main_type":          "Main Operation Type",
        "batch_compress":           "Batch Compress",
        "batch_convert":            "Batch Convert",
        "batch_rename":             "Batch Rename",
        "batch_compress_quality":   "Compression Quality:",
        "batch_radio_pdf2img":      "PDF → Extract All Pages to Images",
        "batch_radio_img2pdf":      "Images → Convert to Individual PDFs",
        "batch_rename_rule":        "Naming Rule:",
        "batch_rename_hint":        "Suggested Parameters:\n[ORIGINAL_NAME] [PAGE_COUNT] [SIZE] [ORDER] [DATE]",
        "batch_start_btn":          "Start / Begin Process",
        "batch_dialog_input":       "Select Source Folder",
        "batch_dialog_output":      "Select Output Folder",
        "batch_log_started":        "--- BATCH PROCESS STARTED ---\nSource: {path}\n",
        "batch_log_ended":          "\n--- PROCESS ENDED ---",
        "batch_progress":           "Processing... {pct}% ({cur}/{total})",
        "batch_done":               "Completed.",
        "batch_result":             "Batch process completed!\nSuccess: {succ}\nErrors: {errs}",
        "batch_result_errors":      "\n\nErrors were written to the .txt report saved by the application. (in {dir} folder)",
        "batch_result_title":       "Done",
        "batch_success_count":      "Success: {succ} // Errors: {errs}",

        # ── Batch Core (Report & Log) ──
        "batch_no_pdf_found":       "No valid PDF files found in source folder.",
        "batch_log_compressed":     "Compressed",
        "batch_log_pages_extracted": "Extracted to pages",
        "batch_log_pdf_created":    "PDF Created",
        "batch_report_date":        "Date",
        "batch_report_total":       "Total Files Processed",
        "batch_report_success":     "Success",
        "batch_report_errors":      "Errors",
        "batch_report_error_details": "ERROR DETAILS",
        "batch_report_no_errors":   "No errors occurred. All operations successful.",

        # ── Settings Tab ──
        "settings_appearance":      "Appearance & Behavior",
        "settings_lang":            "Application Language:",
        "settings_tray":            "Minimize to System Tray when closing (X)",
        "settings_sound":           "Play notification sound when operations complete",
        "settings_file_ops":        "File Operations",
        "settings_default_dir":     "Default Output Folder:",
        "settings_history":         "History & Privacy",
        "settings_clear_history":   "Clear Recent Files History",
        "settings_save_btn":        "Save Settings",
        "settings_cleared":         "History cleared.",
        "settings_saved":           "Settings saved.\nWe recommend restarting the application to apply the language change.",

        # ── System Tray ──
        "tray_open":   "Open",
        "tray_quit":   "Quit",

        # ── Header ──
        "header_subtitle": "Compress  •  Split  •  Merge  •  Edit  •  Convert  •  Security  •  Advanced  •  Batch Process",
        "sidebar_workspace": "WORKSPACE",
        "sidebar_drag_drop": "DRAG AND DROP",
        "page_meta_compress_eyebrow": "QUICK TOOL",
        "page_meta_compress_title": "PDF compression",
        "page_meta_compress_body": "Reduce file size, choose a quality profile, and export the result immediately.",
        "page_meta_organize_eyebrow": "PAGE WORKSPACE",
        "page_meta_organize_title": "Split, merge, edit",
        "page_meta_organize_body": "Keep every page-level operation in one place for splitting, ordering, and combining.",
        "page_meta_convert_eyebrow": "CONVERSION HUB",
        "page_meta_convert_title": "Format converter",
        "page_meta_convert_body": "Move between PDF, Office, and image formats from a single surface.",
        "page_meta_security_eyebrow": "PROTECTION",
        "page_meta_security_title": "Password and watermark",
        "page_meta_security_body": "Protect PDFs, remove passwords, or stamp the document with a watermark.",
        "page_meta_advanced_eyebrow": "ADVANCED TOOLS",
        "page_meta_advanced_title": "Preview, OCR, metadata, signature",
        "page_meta_advanced_body": "Handle higher-level document work in one focused workspace.",
        "page_meta_batch_eyebrow": "AUTOMATION",
        "page_meta_batch_title": "Batch processing",
        "page_meta_batch_body": "Run folder-based compression, conversion, and renaming flows.",
        "feedback_ready_badge": "READY",
        "feedback_ready_title": "Tool is ready",
        "feedback_ready_body": "Pick a file and start the action.",
        "feedback_busy_badge": "WORKING",
        "feedback_busy_title": "Operation is running",
        "feedback_done_badge": "DONE",
        "feedback_error_badge": "ERROR",
        "feedback_info_badge": "INFO",
        "feedback_open_output": "Open Output",
        "feedback_open_folder": "Open Folder",
        "preview_title": "Preview",
        "preview_subtitle": "The selected PDF is summarized here.",
        "preview_open": "Open Viewer",
        "preview_open_folder": "Open Folder",
        "preview_empty_title": "Select a PDF",
        "preview_empty_body": "The first page preview will appear here when a PDF is selected.",
        "preview_empty_sources": "Supported sources: compress, split, merge, edit, security, and advanced tools.",
        "preview_unavailable": "Preview unavailable",
        "preview_pages_mb": "{pages} pages  •  {size:.2f} MB",
        "batch_log_title": "Activity Log",

        # ── Document Scanner ──
        "scanner_title":            "Scan Document",
        "scanner_select_photo":     "Select Photo",
        "scanner_select_hint":      "Choose the photo to use for scanning (JPG, PNG, BMP).",
        "scanner_input_image":      "Input Photo",
        "scanner_output_pdf":       "Output PDF",
        "scanner_scan_mode":        "Scan Style",
        "scanner_mode_original":    "Original (Crop Only)",
        "scanner_mode_clean_doc":   "Clean Document (White Background)",
        "scanner_mode_bw":          "Black & White",
        "scanner_mode_grayscale":   "Grayscale",
        "scanner_mode_sharp":       "Sharp Document",
        "scanner_corners_hint":     "Drag the 4 corners to match the document edges.",
        "scanner_auto_detect":      "Auto Detect",
        "scanner_reset_corners":    "Reset",
        "scanner_rotate_cw":        "↻ Rotate Right",
        "scanner_rotate_ccw":       "↺ Rotate Left",
        "scanner_btn":              "Scan & Create PDF",
        "scanner_running":          "Scanning document...",
        "scanner_done":             "Scan Complete",
        "scanner_fail":             "Scan Failed",
        "scanner_result":           "Document scanned and saved as PDF successfully.\nSaved:\n{output}",
        "scanner_result_multi":     "{count} pages scanned and saved as a single PDF.\nSaved:\n{output}",
        "scanner_no_image":         "Please select a photo first.",
        "scanner_preview":          "Preview",
        "scanner_crop_area":        "Crop Area",
        "scanner_add_photo":        "Add Photo",
        "scanner_remove_photo":     "Remove",
        "scanner_page_count":       "{count} pages",
        "scanner_page_label":       "Page {num}/{total}",
        "scanner_no_pages":         "No photos added yet.",
        "scanner_fullscreen_crop":  "🔍 Fullscreen Crop",
        "scanner_fullscreen_close": "Exit Fullscreen",
        "err_select_valid_image":   "Select a valid image file.",

        # ── Performance Optimization ──
        "perf_cancel":              "Cancel",
        "perf_cancelling":          "Cancelling...",
        "perf_cancelled":           "Cancelled",
        "perf_cancelled_msg":       "Operation cancelled by user.",
        "perf_cancelled_badge":     "CANCELLED",
    }
}

def get_text(key):
    """
    Returns the mapped string depending on the active language from config.
    Falls back to the key itself if no translation is found.
    """
    lang = cfg.get("language", "tr")
    if lang not in _STRINGS:
        lang = "en"

    dic = _STRINGS.get(lang, {})
    return dic.get(key, key)

def _(key):
    """Shorthand for get_text(key)"""
    return get_text(key)
